name: CI

# workflow on push or pull request from main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          # The root LaTeX file to be compiled
          root_file: cv.tex
          
      - name: put file in portfolio
        uses: actions/checkout@v3
        with:
          repository: jekxdevil/jekxdevil.github.io
          path: ./portfolio
          
      - run: |
          ls
          mv cv.pdf ./portfolio
          cd portfolio
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cv.pdf
          git commit -m "docs: update cv"
          git push
          
