name: pdf ci distribution

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
          
      - name: github action for the root latex file to be compiled
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: upload pdf in release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cv.pdf
          body: curriculum vitae pdf file compiled from latex

      # - name: put file in portfolio
